# Generated by Django 3.2.6 on 2022-02-12 03:25

import account.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=10)),
                ('plan', models.CharField(max_length=20)),
                ('district', models.CharField(default='Kathmandu', max_length=30)),
                ('city', models.CharField(default='Baghbazar', max_length=30)),
                ('profile_pic', models.FileField(default='default.png', upload_to='profiles')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('cover_pic', models.FileField(blank=True, default='cover.jpg', null=True, upload_to='covers')),
                ('verified', models.BooleanField(default=False)),
                ('desc', models.TextField(blank=True, max_length=10000, null=True)),
                ('product_sold', models.IntegerField(blank=True, default=0, null=True)),
                ('active', models.BooleanField(blank=True, default=True, null=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('followers', models.ManyToManyField(blank=True, default=[0], related_name='followers', to=settings.AUTH_USER_MODEL)),
                ('following', models.ManyToManyField(blank=True, default=[0], related_name='following', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
