# Generated by Django 3.2.6 on 2022-01-12 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cover_pic',
            field=models.FileField(blank=True, default='cover.jpg', null=True, upload_to='covers'),
        ),
        migrations.AddField(
            model_name='profile',
            name='desc',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
