# Generated by Django 3.2.6 on 2022-01-08 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
