# Generated by Django 3.2.6 on 2022-01-25 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20220112_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='product_sold',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
