# Generated by Django 3.2.6 on 2022-01-25 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_profile_product_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
