# Generated by Django 3.2.6 on 2022-01-29 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_transaction_txn_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='txn_id',
            field=models.CharField(default='Hello', max_length=16),
        ),
    ]
