# Generated by Django 3.2.6 on 2022-01-29 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_transaction_txn_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='txn_id',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
