# Generated by Django 3.2.6 on 2022-02-12 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_profile_active'),
        ('account', '0012_alter_transaction_txn_id'),
    ]

    operations = [
    ]
