# Generated by Django 3.2.6 on 2022-02-13 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_merge_20220212_2258'),
        ('account', '0013_merge_20220213_1128'),
    ]

    operations = [
    ]
