# Generated by Django 3.2.6 on 2022-02-14 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_merge_20220212_2258'),
        ('account', '0015_auto_20220211_1924'),
    ]

    operations = [
    ]
