# Generated by Django 3.2.6 on 2022-02-14 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_auto_20220214_1059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='sender_id',
            new_name='sender',
        ),
    ]
