# Generated by Django 3.2.6 on 2022-02-22 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_merge_20220213_1934'),
        ('account', '0020_alter_transaction_amount'),
    ]

    operations = [
    ]
