# Generated by Django 3.2.6 on 2021-12-30 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20211230_2047'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('image1', models.ImageField(upload_to='static/product_images')),
                ('image2', models.ImageField(upload_to='static/product_images')),
                ('image3', models.ImageField(upload_to='static/product_images')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='slider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.slider'),
        ),
    ]
