# Generated by Django 3.2.6 on 2022-01-07 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20220107_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.ImageField(blank=True, default='def.jpeg', null=True, upload_to='product_images'),
        ),
    ]
