# Generated by Django 3.2.6 on 2021-12-30 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20211230_2055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='picture',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slider',
        ),
        migrations.AddField(
            model_name='product',
            name='image1',
            field=models.ImageField(null=True, upload_to='static/product_images'),
        ),
        migrations.AddField(
            model_name='product',
            name='image2',
            field=models.ImageField(null=True, upload_to='static/product_images'),
        ),
        migrations.AddField(
            model_name='product',
            name='image3',
            field=models.ImageField(null=True, upload_to='static/product_images'),
        ),
        migrations.DeleteModel(
            name='Slider',
        ),
    ]
