# Generated by Django 3.2.6 on 2022-01-17 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_product_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='picture',
            field=models.ImageField(blank=True, default='Electronic.jpg', null=True, upload_to='categories'),
        ),
    ]
