# Generated by Django 3.2.9 on 2022-01-17 06:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0005_comment_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_likes',
            field=models.ManyToManyField(blank=True, related_name='product_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
