# Generated by Django 3.2.6 on 2022-01-20 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_product_product_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='picture',
            field=models.ImageField(default='def.jpeg', upload_to='category_images'),
        ),
    ]
