# Generated by Django 3.2.6 on 2022-01-31 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_category_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='picture',
            field=models.ImageField(default='test.jpeg', upload_to='category_images'),
        ),
    ]
