# Generated by Django 3.2.6 on 2022-02-19 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_category_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image1',
            field=models.ImageField(default=1, upload_to='product_images'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='image2',
            field=models.ImageField(default=1, upload_to='product_images'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='image3',
            field=models.ImageField(default=1, upload_to='product_images'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.ImageField(default='def.jpeg', upload_to='product_images'),
        ),
    ]
