# Generated by Django 3.2.6 on 2022-02-19 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcastnotification',
            name='title',
            field=models.CharField(default='Megaplex Notification', max_length=120),
        ),
    ]
