# Generated by Django 4.0 on 2021-12-28 11:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(db_index=True, max_length=120, validators=[django.core.validators.MinLengthValidator(2)])),
                ('Description', models.CharField(max_length=60, validators=[django.core.validators.MinLengthValidator(30)])),
                ('Image', models.ImageField(upload_to='static/uploads/category')),
            ],
        ),
    ]
